### ISSUE TITLE
Problem compiling OpenMP test with GPU offloading

### ISSUE THREAD

**Issue by simoatze** [clang-ykt/openmp#6]
Hi guys,

I build the clang-ykt LLVM/Clang version and compiled OpenMP with the following command:

`cmake -G Ninja -D CMAKE_INSTALL_PREFIX:PATH=$HOME/usr_linux86-64  -D CMAKE_C_COMPILER=clang  -D CMAKE_CXX_COMPILER=clang++  -D CMAKE_BUILD_TYPE=Debug -D LIBOMPTARGET_DEP_LIBELF_INCLUDE_DIR=$HOME/usr_linux86-64/include -D LIBOMPTARGET_DEP_LIBFFI_INCLUDE_DIR=$HOME/usr_linux86-64/lib/libffi-3.2.1/include -D CMAKE_BUILD_TYPE=Debug -D OPENMP_ENABLE_LIBOMPTARGET=ON ..`

When I try to compile the test "offloading_success.c", I get the following warning:

`warning: Expect degraded performance on the target device due to missing libomptarget-nvptx.bc in library path`

and the error:

```
"/usr/local/cuda/bin/ptxas" -m64 -O0 -v --gpu-name sm_30 --output-file /tmp/offloading_success-01c335.o /tmp/offloading_success-50040e.s -c
ptxas info    : 12 bytes gmem
ptxas info    : Compiling entry function '__omp_offloading_2b_14a2b29_main_l12' for 'sm_30'
ptxas info    : Function properties for __omp_offloading_2b_14a2b29_main_l12
    24 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 20 registers, 336 bytes cmem[0]
ptxas info    : Function properties for __omp_kernel_initialization
    40 bytes stack frame, 20 bytes spill stores, 20 bytes spill loads
 "/home/satzeni/work/LLVM_ykt/LLVM/llvm_build/bin/clang-offload-bundler" -type=a -arch=sm_30 -targets=host-x86_64-unknown-linux-gnu,openmp-nvptx64-nvidia-cuda -inputs=/home/satzeni/usr_linux86-64/lib/libomptarget-nvptx.a -outputs=/tmp/libomptarget-nvptx-cccb3c.o,/tmp/libomptarget-nvptx-d99de8.o -unbundle
ar: No such file or directory
error: 1 extracting the archived object files failed.
 "/usr/bin/cp" /tmp/offloading_success-01c335.o /tmp/offloading_success-01c335-40b44b.cubin
 "/usr/local/cuda/bin/nvlink" -o /tmp/offloading_success-0512bb.out -v -arch sm_30 -L/home/satzeni/work/LLVM_ykt/LLVM/llvm_build/lib -lomptarget-nvptx /tmp/offloading_success-01c335-40b44b.cubin /tmp/libomptarget-nvptx-d99de8.o
nvlink fatal   : Could not open input file '/tmp/libomptarget-nvptx-d99de8.o'
clang-4.0: error: fatbinary command failed with exit code 1 (use -v to see invocation)
```
Do you think I am did something wrong when I build either LLVM/Clangor the OpenMP runtime?
I am on an x86-64 machine with an NVidia Tesla K80 and Cuda 8.0

Thanks!
Simone

**Comment by simoatze** [comment]
Hi guys,

I build the clang-ykt LLVM/Clang version and compiled OpenMP with the following command:

`cmake -G Ninja -D CMAKE_INSTALL_PREFIX:PATH=$HOME/usr_linux86-64  -D CMAKE_C_COMPILER=clang  -D CMAKE_CXX_COMPILER=clang++  -D CMAKE_BUILD_TYPE=Debug -D LIBOMPTARGET_DEP_LIBELF_INCLUDE_DIR=$HOME/usr_linux86-64/include -D LIBOMPTARGET_DEP_LIBFFI_INCLUDE_DIR=$HOME/usr_linux86-64/lib/libffi-3.2.1/include -D CMAKE_BUILD_TYPE=Debug -D OPENMP_ENABLE_LIBOMPTARGET=ON ..`

When I try to compile the test "offloading_success.c", I get the following warning:

`warning: Expect degraded performance on the target device due to missing libomptarget-nvptx.bc in library path`

and the error:

```
"/usr/local/cuda/bin/ptxas" -m64 -O0 -v --gpu-name sm_30 --output-file /tmp/offloading_success-01c335.o /tmp/offloading_success-50040e.s -c
ptxas info    : 12 bytes gmem
ptxas info    : Compiling entry function '__omp_offloading_2b_14a2b29_main_l12' for 'sm_30'
ptxas info    : Function properties for __omp_offloading_2b_14a2b29_main_l12
    24 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 20 registers, 336 bytes cmem[0]
ptxas info    : Function properties for __omp_kernel_initialization
    40 bytes stack frame, 20 bytes spill stores, 20 bytes spill loads
 "/home/satzeni/work/LLVM_ykt/LLVM/llvm_build/bin/clang-offload-bundler" -type=a -arch=sm_30 -targets=host-x86_64-unknown-linux-gnu,openmp-nvptx64-nvidia-cuda -inputs=/home/satzeni/usr_linux86-64/lib/libomptarget-nvptx.a -outputs=/tmp/libomptarget-nvptx-cccb3c.o,/tmp/libomptarget-nvptx-d99de8.o -unbundle
ar: No such file or directory
error: 1 extracting the archived object files failed.
 "/usr/bin/cp" /tmp/offloading_success-01c335.o /tmp/offloading_success-01c335-40b44b.cubin
 "/usr/local/cuda/bin/nvlink" -o /tmp/offloading_success-0512bb.out -v -arch sm_30 -L/home/satzeni/work/LLVM_ykt/LLVM/llvm_build/lib -lomptarget-nvptx /tmp/offloading_success-01c335-40b44b.cubin /tmp/libomptarget-nvptx-d99de8.o
nvlink fatal   : Could not open input file '/tmp/libomptarget-nvptx-d99de8.o'
clang-4.0: error: fatbinary command failed with exit code 1 (use -v to see invocation)
```
Do you think I am did something wrong when I build either LLVM/Clangor the OpenMP runtime?
I am on an x86-64 machine with an NVidia Tesla K80 and Cuda 8.0

Thanks!
Simone

**Comment by simoatze** [comment]
If I don't pass the static library "libomptarget-nvptx.bc" to the compile command I get this undefined references:

nvlink error   : Undefined reference to '__kmpc_kernel_deinit' in '/tmp/offloading_success-445c41-46e13f.cubin'
nvlink error   : Undefined reference to '__kmpc_kernel_init' in '/tmp/offloading_success-445c41-46e13f.cubin'
nvlink error   : Undefined reference to '__kmpc_kernel_parallel' in '/tmp/offloading_success-445c41-46e13f.cubin'

otherwise if I pass the static library the error is on the "clang-offload-bundler".

Any idea? Thanks!

**Comment by doru1004** [comment]
Hi Simone,

You should never have to explicitly pass the .bc library nor the .a library in your compile line. The linking against those libraries is handled for you. If they are not successfully linked in then that's because there is a mismatch between the flags with which the .bc library was compiled and the flags with which your code was compiled. A common source of mismatch is the compute capability. When building the bclib you need to pass a cmake flag which sets the compute capability for libomptarget: -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY=30.

You should also pass this:
-DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_30

to set the default compute capability of CLANG.

Let me know what you get with this changes to your build.

Thanks,

--Doru

**Comment by alexey-bataev** [comment]
Seems to me there is a problem with `ar` tool, compiler is unable to locate it.

**Comment by doru1004** [comment]
Is that tool not available on the machine?

Also can you also provide the full compilation line?

Thanks!
